name: Generate snake animation
on:
schedule:
# execute every 12 hours
- cron:
â€œ**/12***"
workflow_dispatch:
push:
branches:
- master
jobs:
generate:
permissions:
contents: write runs-on:
ubuntu-latest
timeout-minutes: 5
steps:
- name: generate snake.svg
uses: Platane/snk/svg-only@v3 with:
github_user_name: ${{ github.repository_owner }} outputs: dist/snake.svg?palette=github-dark
Screenshot
4-01..6.33 AM
Screenshot
4-01...8.23 AM
Screenshot
4-01...7.56 AM
- name: push snake.sg to the output branch uses: crazy-max/ghaction-github-pages@v3.1.0 with:
target_branch: output build_dir: dist env:
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN 3}
